In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
x = np.array([10,20,30,10,20,40,50,60,70,80,90])
y = np.array([1,3,4,5,6,7,8,9,10,11,23])


In [5]:
x_train,x_test ,y_train ,y_test =  train_test_split(x,y,test_size=0.2)

In [7]:
x_train

array([70, 30, 10, 10, 20, 90, 40, 80])

In [9]:
y_train

array([10,  4,  1,  5,  6, 23,  7, 11])

In [11]:
x_test

array([60, 50, 20])

In [13]:
y_test

array([9, 8, 3])